<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /**
     * @param $serviceId
     *
     * @return array
     */
    public function getWorkerByService($serviceId): array
    {

        $repository = $this->_em->getRepository('AppBundle:Service');
        $query = $repository->createQueryBuilder('s')
            ->innerJoin('s.workers', 'w')
            ->where('s.id = :serviceId')
            ->setParameter('serviceId', $serviceId)
            ->getQuery()->getResult();

        return $query;
    }
}
