<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /**
     * @param $serviceId
     *
     * @return array
     */
    public function findAllGreaterThanPrice($serviceId): array
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT service.title, service.price, service.duration_in_minutes 
            FROM service 
            WHERE service.id = :serviceId'
        )->setParameter($serviceId);

        // returns an array of Product objects
        return $query->execute();
    }
}
