<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Worker;
use AppBundle\Entity\Service;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * WorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerRepository extends EntityRepository
{
}
