<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Worker;
use AppBundle\Entity\Service;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * WorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerRepository extends EntityRepository
{
//    /**
//     * @param int $serviceId
//     *
//     * @return Worker[]
//     */
//    public function getWorkersFromService($serviceId)
//    {
//        $query = $this->_em->createQuery("
//                SELECT DISTINCT w.name
//                FROM AppBundle:Worker AS w
//                LEFT JOIN AppBundle:Service AS s
//                WITH s.worker = s.id
//                GROUP BY s.id = :serviceId;
//                "
//        )->setParameter('serviceId', $serviceId);
//
//        $worker = $query->getResult();
//
//       return $worker;
//    }

//    /**
//     * @param int $serviceId
//     *
//     * @return Worker[]
//     */
//    public function getWorkersFromService($serviceId)
//    {
//        $queryBuilder = $this->_em->createQueryBuilder();
//        $queryBuilder
//            ->select('workers.name')
//            ->from('AppBundle:Worker', 'workers')
//            ->leftJoin(
//                'workers.services',
//                'workers_services',
//                Join::WITH,
//                'workers.id = workers_services.workers_id'
//            )
//            ->leftJoin(
//                'AppBundle:Service',
//                'services',
//                Join::WITH,
//                'serviceId = workers_services.service_id'
//            )
//            ->orderBy('services.id = :serviceId')
//            ->setParameter('serviceId', $serviceId);
//
//        $workers = $queryBuilder->getQuery()->getResult();
//        return $workers;
//    }


}
