app:
    resource: "@AppBundle/Controller"
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

facebook_logout:
    path: /logout

login:
    resource: "@AdminBundle/Controller/DefaultController.php"
    type: annotation
    prefix: /

admin_logout:
    path: /admin/logout

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

add_calendar:
    path: /calendar/reserve-time
    methods: [POST]
    defaults: { _controller: AppBundle:Calendar:calendar}

#update_calendar:
#    path: /calendar/update-time/{id}
#    methods: [GET]
#    defaults: { _controller: AppBundle:Calendar:update}

make_reservation:
    path: /calendar/reserve-time/{serviceId}
    methods: [GET]
    defaults: { _controller: AppBundle:Calendar:makeReservation}
