# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        # Our user class and the algorithm we'll use to encode passwords
        # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
        AppBundle\Entity\User: bcrypt

    providers:
        # Simple example of loading users via Doctrine
        # To load users from somewhere else: http://symfony.com/doc/current/cookbook/security/custom_provider.html
        in_memory:
            memory: ~
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
#                    - app.form_login_authenticator
                    - app.token_authenticator
                    - app.facebook_authenticator
                                # by default, use the start() function from FormLoginAuthenticator
                entry_point:
                    app.token_authenticator
            logout:
                path: /logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/connect/facebook/check, roles: ROLE_USER }



