# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    app.form_login_authenticator:
#        class: AppBundle\Security\FormLoginAuthenticator
#        arguments: ["@service_container"]

    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]

#    app.last_login_subscriber:
#        class: AppBundle\EventListener\LastLoginSubscriber
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - { name: kernel.event_subscriber }

    app.facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true

