# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:

    app.facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true

    AppBundle\EventListener\PostFacebookAuthenticationListener:
        class: AppBundle\EventListener\PostFacebookAuthenticationListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLoginSuccess }

    app.form_authenticator:
        class: AdminBundle\Security\FormAuthenticator
        arguments: ["@router"]


    app_bundle.service.listener:
        class: AppBundle\EventListener\LoadDataListener
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
#            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: addData }

#    app_bundle.service.listener2:
#        class: AppBundle\EventListener\AddDataListener
#        arguments: [ "@doctrine.orm.entity_manager" ]
#        tags:
#            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: addData }
